import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const source = readFileSync('src/app/(main)/analysis/page.tsx', 'utf8');

describe('analysis page auto report wiring', () => {
  it('passes generated report type from the hook to the toast', () => {
    expect(source).toContain('generatedType: autoGeneratedType');
    expect(source).toContain('generatedType={autoGeneratedType}');
  });
});
